"Business info"
type Business {
  "Business id"
  _id: ID
  "Business name"
  name: String
}

type Channel {
  "Channel Id"
  id: String
  "Version software"
  v: String
  "Version configuration"
  c: String
}

type Event {
  "Event Id"
  id: String!
  "Event type"
  type: String!
  "Event user"
  user: String!
}

"Accumulated transaction info"
type AccumulatedTransaction {
  "Accumulated transaction id"
  _id: ID!
  "From business"
  fromBu: String!
  fromBusinessName: String
  "To business"
  toBu: String!
  toBusinessName: String
  "Timestamp"
  timestamp: BigInt
  "Ids of the involved transactions"
  transactionIds: [GroupedTransactions]!
  "Amount"
  amount: BigInt!
}

type GroupedTransactions {
  "Transaction type"
  type: String!
  "Transactions ids"
  ids: [String]
}

"Clearing info"
type Clearing {
  "Clearing id"
  _id: ID
  "Clearing creation timestmap"
  timestamp: BigInt
  "Last update timestmap"
  lastUpdateTimestamp: BigInt
  businessId: String!
  businessName: String
  input: [Movement]
  output: [Movement]
  partialSettlement: PartialSettlement
  accumulatedTransactionIds: [Int]!
  open: Boolean
}

"Money movement"
type Movement {
  "Business ID involved in the movement"
  businessId: String!
  "Business name involved in the movement"
  businessName: String
  "Movement amount"
  amount: Int!
}

"Money movement"
type SettlementMovement {
  "Business ID involved in the movement"
  businessId: String!
  "Business name involved in the movement"
  businessName: String
  "Movement amount"
  amount: Int!
  "Settlement ID"
  settlementId: String!
}

"Partial settlement"
type PartialSettlement {
  input: [SettlementMovement]
  output: [SettlementMovement]
}

"Transaction info"
type Transaction {
  "Transaction id"
  _id: ID!
  "Transaction amount"
  amount: BigInt!
  "From business"
  fromBu: String!
  fromBusinessName: String
  "To business"
  toBu: String!
  toBusinessName: String
  "Timestamp"
  timestamp: BigInt
  "Transaction type"
  type: String!
  "Channel"
  channel: Channel!
  "Event"
  evt: Event!
}

"Hello world sample, please remove"
type HelloWorldACSS {
  "text"
  sn: String!  
}

type Query {
  "Get business"
  getACSSBusiness: Business
  "Get businesses"
  getACSSBusinesses: [Business]
  "Gets the clearings from a business. the value businessId is taken into account if and only if the user has the role system-admin, If a business is not specified, this will return the clearings associated with the business of the user that is performing the request "
  getAllClearingsFromBusiness(page: Int!, count: Int!, businessId: String): [Clearing]
  "Gets the clearing with the indicated ID"
  getClearingById(id: ID!): Clearing
  "Gets the accumulated transactions by ids"
  getAccumulatedTransactionsByIds(page: Int!, count: Int!, ids: [ID!]): [AccumulatedTransaction]
  "Gets transactions by ids"
  getTransactionsByIds(page: Int!, count: Int!, filterType: String, ids: [ID!]): [Transaction]
}

type Subscription {
  "Hello world sample, please remove"
  ACSSHelloWorldSubscription: HelloWorldACSS  
}