"Hello world sample, please remove"
type HelloWorldACSS{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFromACSS: HelloWorldACSS
}

type Subscription {
  "Hello world sample, please remove"
  ACSSHelloWorldSubscription: HelloWorldACSS  
}